[package]
name = "simple-someip"
version = "0.1.0"
edition = "2024"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
chrono = {version="0.4", features = ["serde"]}
thiserror = "2"
tokio = { version = "1", default-features = false, features = [
    "macros",
    "net",
    "rt",
    "sync",
    "time",
], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }

[features]
default = ["client", "server"]
client = ["dep:tokio"]
server = []
